/*
 * Name server list per domain extensions.
 *
 */

#ifndef TLD_SERVER_H
#define TLD_SERVER_H

#ifndef DEFAULT_SERVER
#define DEFAULT_SERVER "whois.iana.org"
#endif

#define VERISIGN_SERVER "whois.verisign-grs.com"

#define CC_SERVER     "whois-servers.net"
#define LU_SERVER     "whois.arin.net"

#define KR_SERVER     "whois.kr"
#define JP_SERVER     "whois.jprs.jp"
#define CN_SERVER     "whois.cnnic.net.cn"

// Non *.whois-servers.net
#define BJ_SERVER     "whois.register.bg"
#define BZ_SERVER     "whois.belizenic.bz"
#define NG_SERVER     "whois.nic.net.ng"
#define SU_SERVER     "whois.tcinet.ru"
#define TC_SERVER     "whois.adamsnames.tc"

const char * tlds[] = {
	// original gtlds
	"com",                      VERISIGN_SERVER,
	"net",                      VERISIGN_SERVER,
	"org",                      "whois.pir.org",
	"gov",                      "whois.dotgov.gov",
	"mil",                      "whois.nic.mil",

	// new gtlds who has un-regular whois server format
	"abarth",                   "whois.afilias-srs.net",
	"abbott",                   "whois.afilias-srs.net",
	"abbvie",                   "whois.afilias-srs.net",
	"aco",                      "whois.afilias-srs.net",
	"active",                   "whois.afilias-srs.net",
	"ads",                      "whois.nic.google",
	"adult",                    "whois.afilias-srs.net",
	"aero",                     "whois.aero",
	"africa",                   "africa-whois.registry.net.za",
	"agakhan",                  "whois.afilias-srs.net",
	"aigo",                     "whois.afilias-srs.net",
	"akdn",                     "whois.afilias-srs.net",
	"alfaromeo",                "whois.afilias-srs.net",
	"allfinanz",                "whois.ksregistry.net",
	"allstate",                 "whois.afilias-srs.net",
	"alsace",                   "whois-alsace.nic.fr",
	"android",                  "whois.nic.google",
	"anquan",                   "whois.teleinfo.cn",
	"app",                      "whois.nic.google",
	"apple",                    "whois.afilias-srs.net",
	"aquarelle",                "whois-aquarelle.nic.fr",
	"archi",                    "whois.afilias.net",
	"arpa",                     DEFAULT_SERVER,
	"asia",                     "whois.nic.asia",
	"audi",                     "whois.afilias-srs.net",
	"audio",                    "whois.uniregistry.net",
	"auto",                     "whois.uniregistry.net",
	"autos",                    "whois.afilias.net",
	"avianca",                  "whois.afilias-srs.net",
	"baidu",                    "whois.gtld.knet.cn",
	"beats",                    "whois.afilias-srs.net",
	"bet",                      "whois.afilias.net",
	"bio",                      "whois.afilias.net",
	"biz",                      "whois.biz",
	"black",                    "whois.afilias.net",
	"blackfriday",              "whois.uniregistry.net",
	"blue",                     "whois.afilias.net",
	"bmw",                      "whois.ksregistry.net",
	"bnpparibas",               "whois.afilias-srs.net",
	"boats",                    "whois.afilias-srs.net",
	"boehringer",               "whois.afilias-srs.net",
	"bom",                      "whois.gtlds.nic.br",
	"boo",                      "whois.nic.google",
	"bostik",                   "whois-bostik.nic.fr",
	"box",                      "whois.aridnrs.net.au",
	"budapest",                 "whois-dub.mm-registry.com",
	"bugatti",                  "whois.afilias-srs.net",
	"buy",                      "whois.afilias-srs.net",
	"cal",                      "whois.nic.google",
	"cam",                      "whois.ksregistry.net",
	"capetown",                 "capetown-whois.registry.net.za",
	"car",                      "whois.uniregistry.net",
	"cars",                     "whois.uniregistry.net",
	"cat",                      "whois.nic.cat",
	"catholic",                 "whois.aridnrs.net.au",
	"cbs",                      "whois.afilias-srs.net",
	"ceb",                      "whois.afilias-srs.net",
	"cern",                     "whois.afilias-srs.net",
	"channel",                  "whois.nic.google",
	"christmas",                "whois.uniregistry.net",
	"chrome",                   "whois.nic.google",
	"chrysler",                 "whois.afilias-srs.net",
	"cipriani",                 "whois.afilias-srs.net",
	"click",                    "whois.uniregistry.net",
	"cologne",                  "whois.ryce-rsp.com",
	"coop",                     "whois.nic.coop",
	"corsica",                  "whois-corsica.nic.fr",
	"country",                  "whois-dub.mm-registry.com",
	"courses",                  "whois.aridnrs.net.au",
	"creditunion",              "whois.afilias-srs.net",
	"dabur",                    "whois.afilias-srs.net",
	"dad",                      "whois.nic.google",
	"datsun",                   "whois.nic.gmo",
	"day",                      "whois.nic.google",
	"dclk",                     "whois.nic.google",
	"desi",                     "whois.ksregistry.net",
	"dev",                      "whois.nic.google",
	"diet",                     "whois.uniregistry.net",
	"docs",                     "whois.nic.google",
	"dodge",                    "whois.afilias-srs.net",
	"doosan",                   "whois.nic.xn--cg4bki",
	"drive",                    "whois.nic.google",
	"durban",                   "durban-whois.registry.net.za",
	"dvag",                     "whois.ksregistry.net",
	"dvr",                      "whois.afilias-srs.net",
	"eat",                      "whois.nic.google",
	"eco",                      "whois.afilias-srs.net",
	"edeka",                    "whois.afilias-srs.net",
	"edu",                      "whois.educause.edu",
	"emerck",                   "whois.afilias-srs.net",
	"epson",                    "whois.aridnrs.net.au",
	"esq",                      "whois.nic.google",
	"esurance",                 "whois.afilias-srs.net",
	"etisalat",                 "whois.centralnic.com",
	"extraspace",               "whois.afilias-srs.net",
	"fage",                     "whois.afilias-srs.net",
	"fiat",                     "whois.afilias-srs.net",
	"fido",                     "whois.afilias-srs.net",
	"final",                    "whois.gtlds.nic.br",
	"flowers",                  "whois.uniregistry.net",
	"fly",                      "whois.nic.google",
	"foo",                      "whois.nic.google",
	"fresenius",                "whois.ksregistry.net",
	"fujitsu",                  "whois.nic.gmo",
	"game",                     "whois.uniregistry.net",
	"gbiz",                     "whois.nic.google",
	"gea",                      "whois.afilias-srs.net",
	"gift",                     "whois.uniregistry.net",
	"gle",                      "whois.nic.google",
	"globo",                    "whois.gtlds.nic.br",
	"gmail",                    "whois.nic.google",
	"gmx",                      "whois-fe1.gmx.tango.knipp.de",
	"godaddy",                  "whois.afilias-srs.net",
	"goo",                      "whois.nic.gmo",
	"goog",                     "whois.nic.google",
	"green",                    "whois.afilias.net",
	"guge",                     "whois.nic.google",
	"guitars",                  "whois.uniregistry.net",
	"hangout",                  "whois.nic.google",
	"help",                     "whois.uniregistry.net",
	"here",                     "whois.nic.google",
	"hermes",                   "whois.afilias-srs.net",
	"hiphop",                   "whois.uniregistry.net",
	"hisamitsu",                "whois.nic.gmo",
	"hitachi",                  "whois.nic.gmo",
	"hiv",                      "whois.uniregistry.net",
	"homes",                    "whois.afilias-srs.net",
	"hosting",                  "whois.uniregistry.net",
	"how",                      "whois.nic.google",
	"ikano",                    "whois.ikano.tld-box.at",
	"imamat",                   "whois.afilias-srs.net",
	"infiniti",                 "whois.nic.gmo",
	"info",                     "whois.afilias.net",
	"ing",                      "whois.nic.google",
	"int",                      DEFAULT_SERVER,
	"ismaili",                  "whois.afilias-srs.net",
	"ist",                      "whois.afilias-srs.net",
	"istanbul",                 "whois.afilias-srs.net",
	"itv",                      "whois.afilias-srs.net",
	"jcb",                      "whois.nic.gmo",
	"jcp",                      "whois.afilias-srs.net",
	"jeep",                     "whois.afilias-srs.net",
	"jll",                      "whois.afilias-srs.net",
	"jobs",                     "whois.nic.jobs",
	"joburg",                   "joburg-whois.registry.net.za",
	"juegos",                   "whois.uniregistry.net",
	"kim",                      "whois.afilias.net",
	"koeln",                    "whois.ryce-rsp.com",
	"krd",                      "whois.aridnrs.net.au",
	"lamborghini",              "whois.afilias-srs.net",
	"lancaster",                "whois-lancaster.nic.fr",
	"lancia",                   "whois.afilias-srs.net",
	"lasalle",                  "whois.afilias-srs.net",
	"leclerc",                  "whois-leclerc.nic.fr",
	"lgbt",                     "whois.afilias.net",
	"link",                     "whois.uniregistry.net",
	"llc",                      "whois.afilias.net",
	"lol",                      "whois.uniregistry.net",
	"lotto",                    "whois.afilias.net",
	"ltda",                     "whois.afilias-srs.net",
	"madrid",                   "whois.madrid.rs.corenic.net",
	"map",                      "whois.nic.google",
	"marriott",                 "whois.afilias-srs.net",
	"meet",                     "whois.nic.google",
	"melbourne",                "whois.aridnrs.net.au",
	"meme",                     "whois.nic.google",
	"mini",                     "whois.ksregistry.net",
	"mit",                      "whois.afilias-srs.net",
	"mitsubishi",               "whois.nic.gmo",
	"mma",                      "whois-mma.nic.fr",
	"mobi",                     "whois.afilias.net",
	"mom",                      "whois.uniregistry.net",
	"mopar",                    "whois.afilias-srs.net",
	"motorcycles",              "whois.afilias-srs.net",
	"mov",                      "whois.nic.google",
	"movistar",                 "whois-fe.movistar.tango.knipp.de",
	"museum",                   "whois.nic.museum",
	"name",                     "whois.nic.name",
	"natura",                   "whois.afilias-srs.net",
	"new",                      "whois.nic.google",
	"nexus",                    "whois.nic.google",
	"ngo",                      "whois.publicinterestregistry.net",
	"nissan",                   "whois.nic.gmo",
	"nokia",                    "whois.afilias-srs.net",
	"nowruz",                   "whois.agitsys.net",
	"nra",                      "whois.afilias-srs.net",
	"ong",                      "whois.publicinterestregistry.net",
	"onl",                      "whois.afilias-srs.net",
	"organic",                  "whois.afilias.net",
	"orientexpress",            "whois.afilias-srs.net",
	"origin",                   "whois.afilias-srs.net",
	"ovh",                      "whois-ovh.nic.fr",
	"page",                     "whois.nic.google",
	"panasonic",                "whois.nic.gmo",
	"paris",                    "whois-paris.nic.fr",
	"pars",                     "whois.agitsys.net",
	"pet",                      "whois.afilias.net",
	"phd",                      "whois.nic.google",
	"photo",                    "whois.uniregistry.net",
	"pics",                     "whois.uniregistry.net",
	"pink",                     "whois.afilias.net",
	"pioneer",                  "whois.nic.gmo",
	"play",                     "whois.nic.google",
	"pohl",                     "whois.ksregistry.net",
	"poker",                    "whois.afilias.net",
	"politie",                  "whois.nicpolitie",
	"porn",                     "whois.afilias-srs.net",
	"post",                     "whois.dotpostregistry.net",
	"pro",                      "whois.afilias.net",
	"prod",                     "whois.nic.google",
	"prof",                     "whois.nic.google",
	"progressive",              "whois.afilias-srs.net",
	"promo",                    "whois.afilias.net",
	"property",                 "whois.uniregistry.net",
	"protection",               "whois.centralnic.com",
	"pwc",                      "whois.afilias-srs.net",
	"red",                      "whois.afilias.net",
	"redumbrella",              "whois.afilias-srs.net",
	"rich",                     "whois.afilias-srs.net",
	"rio",                      "whois.gtlds.nic.br",
	"rmit",                     "whois.aridnrs.net.au",
	"rogers",                   "whois.afilias-srs.net",
	"rsvp",                     "whois.nic.google",
	"rugby",                    "whois.centralnic.com",
	"saarland",                 "whois.ksregistry.net",
	"samsung",                  "whois.nic.xn--cg4bki",
	"saxo",                     "whois.aridnrs.net.au",
	"schaeffler",               "whois.afilias-srs.net",
	"search",                   "whois.nic.google",
	"sew",                      "whois.afilias-srs.net",
	"sex",                      "whois.afilias-srs.net",
	"sexy",                     "whois.uniregistry.net",
	"sharp",                    "whois.nic.gmo",
	"shaw",                     "whois.afilias-srs.net",
	"shia",                     "whois.agitsys.net",
	"shiksha",                  "whois.afilias.net",
	"shouji",                   "whois.teleinfo.cn",
	"showtime",                 "whois.afilias-srs.net",
	"shriram",                  "whois.afilias-srs.net",
	"ski",                      "whois.afilias.net",
	"sncf",                     "whois-sncf.nic.fr",
	"soy",                      "whois.nic.google",
	"spiegel",                  "whois.ksregistry.net",
	"srl",                      "whois.afilias-srs.net",
	"srt",                      "whois.afilias-srs.net",
	"stada",                    "whois.afilias-srs.net",
	"stockholm",                "whois.afilias-srs.net",
	"tattoo",                   "whois.uniregistry.net",
	"tci",                      "whois.agitsys.net",
	"tel",                      "whois.nic.tel",
	"telefonica",               "whois-fe.telefonica.tango.knipp.de",
	"temasek",                  "whois.afilias-srs.net",
	"tiia",                     "whois.nic.tiia",
	"total",                    "whois-total.nic.fr",
	"travel",                   "whois.nic.travel",
	"travelers",                "whois.afilias-srs.net",
	"travelersinsurance",       "whois.afilias-srs.net",
	"trv",                      "whois.afilias-srs.net",
	"tui",                      "whois.ksregistry.net",
	"uconnect",                 "whois.afilias-srs.net",
	"uol",                      "whois.gtlds.nic.br",
	"vegas",                    "whois.afilias-srs.net",
	"vig",                      "whois.afilias-srs.net",
	"viking",                   "whois.afilias-srs.net",
	"volkswagen",               "whois.afilias-srs.net",
	"vote",                     "whois.afilias.net",
	"voting",                   "whois.voting.tld-box.at",
	"voto",                     "whois.afilias.net",
	"wang",                     "whois.gtld.knet.cn",
	"xihuan",                   "whois.teleinfo.cn",
	"xn--1qqw23a",              "whois.ngtld.cn",                   // 佛山
	"xn--30rr7y",               "whois.gtld.knet.cn",               // 慈善
	"xn--3bst00m",              "whois.gtld.knet.cn",               // 集团
	"xn--3ds443g",              "whois.teleinfo.cn",                // 在线
	"xn--3e0b707e",             KR_SERVER,                          // 한국
	"xn--45brj9c",              "whois.inregistry.net",             // ভারত
	"xn--4gbrim",               "whois.afilias-srs.net",            // موقع
	"xn--55qw42g",              "whois.conac.cn",                   // 公益
	"xn--55qx5d",               "whois.ngtld.cn",                   // 公司
	"xn--6frz82g",              "whois.afilias.net",                // 移动
	"xn--6qq986b3xl",           "whois.gtld.knet.cn",               // 我爱你
	"xn--80ao21a",              "whois.nic.kz",                     // қаз
	"xn--80aqecdr1a",           "whois.aridnrs.net.au",             // католик
	"xn--80asehdb",             "whois.online.rs.corenic.net",      // онлайн
	"xn--80aswg",               "whois.online.rs.corenic.net",      // сайт
	"xn--8y0a063a",             "whois.imena.bg",                   // 联通
	"xn--90a3ac",               "whois.rnids.rs",                   // срб
	"xn--90ais",                "whois.cctld.by",                   // бел
	"xn--9et52u",               "whois.gtld.knet.cn",               // 时尚
	"xn--b4w605ferd",           "whois.afilias-srs.net",            // 淡马锡
	"xn--c1avg",                "whois.publicinterestregistry.net", // орг
	"xn--cg4bki",               KR_SERVER,                          // 삼성
	"xn--clchc0ea0b2g2a9gcd",   "whois.sgnic.sg",                   // சிங்கப்பூர்
	"xn--czru2d",               "whois.gtld.knet.cn",               // 商城
	"xn--d1alf",                "whois.marnet.mk",                  // мкд
	"xn--e1a4c",                "whois.eu",                         // ею
	"xn--fiq228c5hs",           "whois.teleinfo.cn",                // 中文网
	"xn--fiq64b",               "whois.gtld.knet.cn",               // 中信
	"xn--fiqs8s",               "cwhois.cnnic.cn",                  // 中国
	"xn--fiqz9s",               "cwhois.cnnic.cn",                  // 中國
	"xn--flw351e",              "whois.nic.google",                 // 谷歌
	"xn--fpcrj9c3d",            "whois.inregistry.net",             // భారత్
	"xn--fzc2c9e2c",            "whois.nic.lk",                     // ලංකා
	"xn--g2xx48c",              "whois.afilias-srs.net",            // 购物
	"xn--gecrj9c",              "whois.inregistry.net",             // ભારત
	"xn--h2brj9c",              "whois.inregistry.net",             // भारत
	"xn--i1b6b1a6a2e",          "whois.publicinterestregistry.net", // संगठन
	"xn--io0a7i",               "whois.ngtld.cn",                   // 网络
	"xn--j1amh",                "whois.dotukr.com",                 // укр
	"xn--j6w193g",              "whois.hkirc.hk",                   // 香港
	"xn--kprw13d",              "whois.twnic.net.tw",               // 台湾
	"xn--kpry57d",              "whois.twnic.net.tw",               // 台灣
	"xn--lgbbat1ad8j",          "whois.nic.dz",                     // الجزائر
	"xn--mgb9awbf",             "whois.registry.om",                // عمان
	"xn--mgba3a4f16a",          "whois.nic.ir",                     // ایران
	"xn--mgbaakc7dvf",          "whois.centralnic.com",             // اتصالات
	"xn--mgbaam7a8h",           "whois.aeda.net.ae",                // امارات
	"xn--mgbab2bd",             "whois.bazaar.coreregistry.net",    // بازار
	"xn--mgbbh1a71e",           "whois.inregistry.net",             // بھارت
	"xn--mgbca7dzdo",           "whois.afilias-srs.net",            // ابوظبي
	"xn--mgberp4a5d4ar",        "whois.nic.net.sa",                 // السعودية
	"xn--mgbi4ecexp",           "whois.aridnrs.net.au",             // كاثوليك
	"xn--mgbt3dhd",             "whois.agitsys.net",                // همراه
	"xn--mgbtx2b",              "whois.cmc.iq",                     // عراق
	"xn--mgbx4cd0ab",           "whois.mynic.my",                   // مليسيا
	"xn--mix891f",              "whois.monic.mo",                   // 澳門
	"xn--node",                 "whois.itdc.ge",                    // გე
	"xn--nqv7f",                "whois.publicinterestregistry.net", // 机构
	"xn--o3cw4h",               "whois.thnic.co.th",                // ไทย
	"xn--ogbpf8fl",             "whois.tld.sy",                     // سورية
	"xn--p1ai",                 "whois.tcinet.ru",                  // рф
	"xn--q9jyb4c",              "whois.nic.google",                 // みんな
	"xn--qcka1pmc",             "whois.nic.google",                 // グーグル
	"xn--s9brj9c",              "whois.inregistry.net",             // ਭਾਰਤ
	"xn--ses554g",              "whois.registry.knet.cn",           // 网址
	"xn--tiq49xqyj",            "whois.aridnrs.net.au",             // 天主教
	"xn--vermgensberater-ctb",  "whois.ksregistry.net",             // vermögensberater
	"xn--vermgensberatung-pwb", "whois.ksregistry.net",             // vermögensberatung
	"xn--vuq861b",              "whois.teleinfo.cn",                // 信息
	"xn--wgbh1c",               "whois.dotmasr.eg",                 // مصر
	"xn--wgbl6a",               "whois.registry.qa",                // قطر
	"xn--xhq521b",              "whois.teleinfo.cn",                // 广东
	"xn--xkc2al3hye2a",         "whois.nic.lk",                     // இலங்கை
	"xn--xkc2dl3a5ee0h",        "whois.inregistry.net",             // இந்தியா
	"xn--y9a3aq",               "whois.amnic.net",                  // հայ
	"xn--yfro4i67o",            "whois.sgnic.sg",                   // 新加坡
	"xn--ygbi2ammx",            "whois.pnina.ps",                   // فلسطين
	"xn--zfr164b",              "whois.conac.cn",                   // 政务
	"xxx",                      "whois.nic.xxx",
	"yachts",                   "whois.afilias-srs.net",
	"yodobashi",                "whois.nic.gmo",
	"youtube",                  "whois.nic.google",
	"yun",                      "whois.teleinfo.cn",
	"zara",                     "whois.afilias-srs.net",
	"zip",                      "whois.nic.google",
	"zuerich",                  "whois.ksregistry.net",

	// no whois server lists
	"aaa",                      DEFAULT_SERVER,
	"abb",                      DEFAULT_SERVER,
	"able",                     DEFAULT_SERVER,
	"accenture",                DEFAULT_SERVER,
	"adac",                     DEFAULT_SERVER,
	"aetna",                    DEFAULT_SERVER,
	"aig",                      DEFAULT_SERVER,
	"americanexpress",          DEFAULT_SERVER,
	"amex",                     DEFAULT_SERVER,
	"amica",                    DEFAULT_SERVER,
	"analytics",                DEFAULT_SERVER,
	"aramco",                   DEFAULT_SERVER,
	"in-addr.arpa",             DEFAULT_SERVER,
	"athleta",                  DEFAULT_SERVER,
	"audible",                  DEFAULT_SERVER,
	"author",                   DEFAULT_SERVER,
	"aws",                      DEFAULT_SERVER,
	"axa",                      DEFAULT_SERVER,
	"azure",                    DEFAULT_SERVER,
	"baby",                     DEFAULT_SERVER,
	"banamex",                  DEFAULT_SERVER,
	"bananarepublic",           DEFAULT_SERVER,
	"baseball",                 DEFAULT_SERVER,
	"bharti",                   DEFAULT_SERVER,
	"bing",                     DEFAULT_SERVER,
	"bloomberg",                DEFAULT_SERVER,
	"book",                     DEFAULT_SERVER,
	"booking",                  DEFAULT_SERVER,
	"bot",                      DEFAULT_SERVER,
	"call",                     DEFAULT_SERVER,
	"calvinklein",              DEFAULT_SERVER,
	"caravan",                  DEFAULT_SERVER,
	"cartier",                  DEFAULT_SERVER,
	"cbn",                      DEFAULT_SERVER,
	"cbre",                     DEFAULT_SERVER,
	"chase",                    DEFAULT_SERVER,
	"circle",                   DEFAULT_SERVER,
	"cisco",                    DEFAULT_SERVER,
	"citadel",                  DEFAULT_SERVER,
	"citi",                     DEFAULT_SERVER,
	"citic",                    DEFAULT_SERVER,
	"edu.cn",                   DEFAULT_SERVER,
	"coupon",                   DEFAULT_SERVER,
	"crown",                    DEFAULT_SERVER,
	"crs",                      DEFAULT_SERVER,
	"deal",                     DEFAULT_SERVER,
	"dealer",                   DEFAULT_SERVER,
	"dell",                     DEFAULT_SERVER,
	"dhl",                      DEFAULT_SERVER,
	"discover",                 DEFAULT_SERVER,
	"dnp",                      DEFAULT_SERVER,
	"duns",                     DEFAULT_SERVER,
	"dupont",                   DEFAULT_SERVER,
	"earth",                    DEFAULT_SERVER,
	"epost",                    DEFAULT_SERVER,
	"farmers",                  DEFAULT_SERVER,
	"fast",                     DEFAULT_SERVER,
	"ferrero",                  DEFAULT_SERVER,
	"fire",                     DEFAULT_SERVER,
	"flickr",                   DEFAULT_SERVER,
	"flir",                     DEFAULT_SERVER,
	"food",                     DEFAULT_SERVER,
	"ford",                     DEFAULT_SERVER,
	"fox",                      DEFAULT_SERVER,
	"free",                     DEFAULT_SERVER,
	"frontier",                 DEFAULT_SERVER,
	"ftr",                      DEFAULT_SERVER,
	"gap",                      DEFAULT_SERVER,
	"gmoregistry",              DEFAULT_SERVER,
	"got",                      DEFAULT_SERVER,
	"grainger",                 DEFAULT_SERVER,
	"grocery",                  DEFAULT_SERVER,
	"guardian",                 DEFAULT_SERVER,
	"gucci",                    DEFAULT_SERVER,
	"hair",                     DEFAULT_SERVER,
	"hbo",                      DEFAULT_SERVER,
	"health",                   DEFAULT_SERVER,
	"homegoods",                DEFAULT_SERVER,
	"homesense",                DEFAULT_SERVER,
	"honeywell",                DEFAULT_SERVER,
	"hot",                      DEFAULT_SERVER,
	"hoteles",                  DEFAULT_SERVER,
	"hotels",                   DEFAULT_SERVER,
	"hotmail",                  DEFAULT_SERVER,
	"hsbc",                     DEFAULT_SERVER,
	"hyatt",                    DEFAULT_SERVER,
	"ieee",                     DEFAULT_SERVER,
	"imdb",                     DEFAULT_SERVER,
	"intel",                    DEFAULT_SERVER,
	"intuit",                   DEFAULT_SERVER,
	"ipiranga",                 DEFAULT_SERVER,
	"itau",                     DEFAULT_SERVER,
	"jmp",                      DEFAULT_SERVER,
	"jnj",                      DEFAULT_SERVER,
	"jot",                      DEFAULT_SERVER,
	"joy",                      DEFAULT_SERVER,
	"jpmorgan",                 DEFAULT_SERVER,
	"jprs",                     DEFAULT_SERVER,
	"kinder",                   DEFAULT_SERVER,
	"kindle",                   DEFAULT_SERVER,
	"kpmg",                     DEFAULT_SERVER,
	"kpn",                      DEFAULT_SERVER,
	"kred",                     DEFAULT_SERVER,
	"lanxess",                  DEFAULT_SERVER,
	"lifeinsurance",            DEFAULT_SERVER,
	"like",                     DEFAULT_SERVER,
	"lilly",                    DEFAULT_SERVER,
	"lincoln",                  DEFAULT_SERVER,
	"living",                   DEFAULT_SERVER,
	"loft",                     DEFAULT_SERVER,
	"lupin",                    DEFAULT_SERVER,
	"maif",                     DEFAULT_SERVER,
	"marshalls",                DEFAULT_SERVER,
	"mattel",                   DEFAULT_SERVER,
	"merckmsd",                 DEFAULT_SERVER,
	"microsoft",                DEFAULT_SERVER,
	"mint",                     DEFAULT_SERVER,
	"mlb",                      DEFAULT_SERVER,
	"mobily",                   DEFAULT_SERVER,
	"moi",                      DEFAULT_SERVER,
	"montblanc",                DEFAULT_SERVER,
	"moto",                     DEFAULT_SERVER,
	"msd",                      DEFAULT_SERVER,
	"mutual",                   DEFAULT_SERVER,
	"nba",                      DEFAULT_SERVER,
	"netflix",                  DEFAULT_SERVER,
	"neustar",                  DEFAULT_SERVER,
	"nfl",                      DEFAULT_SERVER,
	"nhk",                      DEFAULT_SERVER,
	"nike",                     DEFAULT_SERVER,
	"northwesternmutual",       DEFAULT_SERVER,
	"now",                      DEFAULT_SERVER,
	"ntt",                      DEFAULT_SERVER,
	"office",                   DEFAULT_SERVER,
	"oldnavy",                  DEFAULT_SERVER,
	"open",                     DEFAULT_SERVER,
	"otsuka",                   DEFAULT_SERVER,
	"passagens",                DEFAULT_SERVER,
	"pay",                      DEFAULT_SERVER,
	"pfizer",                   DEFAULT_SERVER,
	"pharmacy",                 DEFAULT_SERVER,
	"piaget",                   DEFAULT_SERVER,
	"pictet",                   DEFAULT_SERVER,
	"pin",                      DEFAULT_SERVER,
	"ping",                     DEFAULT_SERVER,
	"pramerica",                DEFAULT_SERVER,
	"praxi",                    DEFAULT_SERVER,
	"prime",                    DEFAULT_SERVER,
	"pru",                      DEFAULT_SERVER,
	"prudential",               DEFAULT_SERVER,
	"qpon",                     DEFAULT_SERVER,
	"qvc",                      DEFAULT_SERVER,
	"read",                     DEFAULT_SERVER,
	"realtor",                  DEFAULT_SERVER,
	"ren",                      DEFAULT_SERVER,
	"rocher",                   DEFAULT_SERVER,
	"room",                     DEFAULT_SERVER,
	"safe",                     DEFAULT_SERVER,
	"safety",                   DEFAULT_SERVER,
	"sakura",                   DEFAULT_SERVER,
	"sas",                      DEFAULT_SERVER,
	"save",                     DEFAULT_SERVER,
	"secure",                   DEFAULT_SERVER,
	"sener",                    DEFAULT_SERVER,
	"silk",                     DEFAULT_SERVER,
	"skype",                    DEFAULT_SERVER,
	"smile",                    DEFAULT_SERVER,
	"sohu",                     DEFAULT_SERVER,
	"song",                     DEFAULT_SERVER,
	"spot",                     DEFAULT_SERVER,
	"staples",                  DEFAULT_SERVER,
	"statefarm",                DEFAULT_SERVER,
	"stream",                   DEFAULT_SERVER,
	"suzuki",                   DEFAULT_SERVER,
	"swiftcover",               DEFAULT_SERVER,
	"talk",                     DEFAULT_SERVER,
	"taobao",                   DEFAULT_SERVER,
	"target",                   DEFAULT_SERVER,
	"tdk",                      DEFAULT_SERVER,
	"tjmaxx",                   DEFAULT_SERVER,
	"tjx",                      DEFAULT_SERVER,
	"tkmaxx",                   DEFAULT_SERVER,
	"tmall",                    DEFAULT_SERVER,
	"tube",                     DEFAULT_SERVER,
	"tunes",                    DEFAULT_SERVER,
	"tushu",                    DEFAULT_SERVER,
	"bl.uk",                    DEFAULT_SERVER,
	"british-library.uk",       DEFAULT_SERVER,
	"icnet.uk",                 DEFAULT_SERVER,
	"jet.uk",                   DEFAULT_SERVER,
	"mod.uk",                   DEFAULT_SERVER,
	"nhs.uk",                   DEFAULT_SERVER,
	"nls.uk",                   DEFAULT_SERVER,
	"parliament.uk",            DEFAULT_SERVER,
	"police.uk",                DEFAULT_SERVER,
	"unicom",                   DEFAULT_SERVER,
	"uno",                      DEFAULT_SERVER,
	"com.uy",                   DEFAULT_SERVER,
	"vivo",                     DEFAULT_SERVER,
	"vuelos",                   DEFAULT_SERVER,
	"wanggou",                  DEFAULT_SERVER,
	"watches",                  DEFAULT_SERVER,
	"weather",                  DEFAULT_SERVER,
	"weatherchannel",           DEFAULT_SERVER,
	"weir",                     DEFAULT_SERVER,
	"williamhill",              DEFAULT_SERVER,
	"windows",                  DEFAULT_SERVER,
	"winners",                  DEFAULT_SERVER,
	"wow",                      DEFAULT_SERVER,
	"xbox",                     DEFAULT_SERVER,
	"xn--1ck2e1b",              DEFAULT_SERVER,
	"xn--2scrj9c",              DEFAULT_SERVER,
	"xn--45br5cyl",             DEFAULT_SERVER,
	"xn--45q11c",               DEFAULT_SERVER,
	"xn--54b7fta0cc",           DEFAULT_SERVER,
	"xn--90ae",                 DEFAULT_SERVER,
	"xn--bck1b9a5dre4c",        DEFAULT_SERVER,
	"xn--cck2b3b",              DEFAULT_SERVER,
	"xn--eckvdtc9d",            DEFAULT_SERVER,
	"xn--fct429k",              DEFAULT_SERVER,
	"xn--gckr3f0f",             DEFAULT_SERVER,
	"xn--gk3at1e",              DEFAULT_SERVER,
	"xn--h2breg3eve",           DEFAULT_SERVER,
	"xn--h2brj9c8c",            DEFAULT_SERVER,
	"xn--imr513n",              DEFAULT_SERVER,
	"xn--jvr189m",              DEFAULT_SERVER,
	"xn--kpu716f",              DEFAULT_SERVER,
	"xn--l1acc",                DEFAULT_SERVER,
	"xn--mgba3a3ejt",           DEFAULT_SERVER,
	"xn--mgbai9azgqp6j",        DEFAULT_SERVER,
	"xn--mgbayh7gpa",           DEFAULT_SERVER,
	"xn--mgbb9fbpob",           DEFAULT_SERVER,
	"xn--mgbbh1a",              DEFAULT_SERVER,
	"xn--mgbc0a9azcg",          DEFAULT_SERVER,
	"xn--mgbgu82a",             DEFAULT_SERVER,
	"xn--mgbpl2fh",             DEFAULT_SERVER,
	"xn--nyqy26a",              DEFAULT_SERVER,
	"xn--otu796d",              DEFAULT_SERVER,
	"xn--pbt977c",              DEFAULT_SERVER,
	"xn--pgbs0dh",              DEFAULT_SERVER,
	"xn--qxam",                 DEFAULT_SERVER,
	"xn--rhqv96g",              DEFAULT_SERVER,
	"xn--rovu88b",              DEFAULT_SERVER,
	"xn--rvc1e0am3e",           DEFAULT_SERVER,
	"yahoo",                    DEFAULT_SERVER,
	"yamaxun",                  DEFAULT_SERVER,
	"yandex",                   DEFAULT_SERVER,
	"you",                      DEFAULT_SERVER,
	"zappos",                   DEFAULT_SERVER,
	"zero",                     DEFAULT_SERVER,
	"zippo",                    DEFAULT_SERVER,
	NULL, NULL
};

const char * two_depth_tlds[] = {
	".ac.uk",                   "whois.ja.net",
	".ac.za",                   "whois.ac.za",
	".ae.org",                  "whois.centralnic.com",
	".aeroport.fr",             "whois.smallregistry.net",
	".africa.com",              "whois.centralnic.com",
	".alt.za",                  "whois.alt.za",
	".ar.com",                  "whois.centralnic.com",
	".avocat.fr",               "whois.smallregistry.net",
	".br.com",                  "whois.centralnic.com",
	".chambagri.fr",            "whois.smallregistry.net",
	".chirurgiens-dentistes.fr", "whois.smallregistry.net",
	".cn.com",                  "whois.centralnic.com",
	".co.ca",                   "whois.co.ca",
	".co.com",                  "whois.centralnic.net",
	".co.pl",                   "whois.co.pl",
	".co.za",                   "coza-whois.registry.net.za",
	".com.de",                  "whois.centralnic.com",
	".com.se",                  "whois.centralnic.com",
	".de.com",                  "whois.centralnic.com",
	".e164.arpa",               "whois.ripe.net",
	".edu.ru",                  "whois.informika.ru",
	".eu.com",                  "whois.centralnic.com",
	".eu.org",                  "whois.eu.org",
	".experts-comptables.fr",   "whois.smallregistry.net",
	".gb.com",                  "whois.centralnic.com",
	".gb.net",                  "whois.centralnic.com",
	".geometre-expert.fr",      "whois.smallregistry.net",
	".gov.uk",                  "whois.ja.net",
	".gov.za",                  "whois.gov.za",
	".gr.com",                  "whois.centralnic.com",
	".hk.com",                  "whois.registry.hk.com",
	".hk.org",                  "whois.registry.hk.com",
	".hu.com",                  "whois.centralnic.com",
	".hu.net",                  "whois.centralnic.com",
	".in.net",                  "whois.centralnic.com",
	".in.ua",                   "whois.in.ua",
	".inc.hk",                  "whois.registry.hk.com",
	".jp.net",                  "whois.centralnic.com",
	".jpn.com",                 "whois.centralnic.com",
	".kr.com",                  "whois.centralnic.com",
	".ltd.hk",                  "whois.registry.hk.com",
	".medecin.fr",              "whois.smallregistry.net",
	".net.za",                  "net-whois.registry.net.za",
	".no.com",                  "whois.centralnic.com",
	".notaires.fr",             "whois.smallregistry.net",
	".org.za",                  "org-whois.registry.net.za",
	".pharmacien.fr",           "whois.smallregistry.net",
	".port.fr",                 "whois.smallregistry.net",
	".priv.at",                 "whois.nic.priv.at",
	".qc.com",                  "whois.centralnic.com",
	".ru.com",                  "whois.centralnic.com",
	".sa.com",                  "whois.centralnic.com",
	".se.com",                  "whois.centralnic.com",
	".se.net",                  "whois.centralnic.com",
	".uk.com",                  "whois.centralnic.com",
	".uk.net",                  "whois.centralnic.com",
	".us.com",                  "whois.centralnic.com",
	".us.org",                  "whois.centralnic.com",
	".uy.com",                  "whois.centralnic.com",
	".veterinaire.fr",          "whois.smallregistry.net",
	".web.za",                  "web-whois.registry.net.za",
	".za.bz",                   "whois.centralnic.com",
	".za.com",                  "whois.centralnic.com",
	".za.net",                  "whois.za.net",
	".za.org",                  "whois.za.org",
	NULL, NULL
};

const char * cc_tlds[] = {
	"ac",                       "whois.nic.ac",
	"ad",                       "ad.whois-servers.net",
	"ae",                       "whois.aeda.net.ae",
	"af",                       "whois.nic.af",
	"ag",                       "whois.nic.ag",
	"ai",                       "whois.nic.ai",
	"al",                       "al.whois-servers.net",
	"am",                       "whois.amnic.net",
	"ao",                       DEFAULT_SERVER,
	"aq",                       DEFAULT_SERVER,
	"ar",                       "whois.nic.ar",
	"as",                       "whois.nic.as",
	"at",                       "whois.nic.at",
	"au",                       "whois.auda.org.au",
	"aw",                       "whois.nic.aw",
	"ax",                       "whois.ax",
	"az",                       "az.whois-servers.net",
	"ba",                       "ba.whois-servers.net",
	"bb",                       DEFAULT_SERVER,
	"bd",                       DEFAULT_SERVER,
	"be",                       "whois.dns.be",
	"bf",                       "whois.nic.bf",
	"bg",                       "whois.register.bg",
	"bh",                       DEFAULT_SERVER,
	"bi",                       "whois1.nic.bi",
	"bj",                       "whois.nic.bj",
	"bm",                       DEFAULT_SERVER,
	"bn",                       "whois.bnnic.bn",
	"bo",                       "whois.nic.bo",
	"br",                       "whois.registro.br",
	"bs",                       DEFAULT_SERVER,
	"bt",                       DEFAULT_SERVER,
	"bv",                       DEFAULT_SERVER,
	"bw",                       "whois.nic.net.bw",
	"by",                       "whois.cctld.by",
	"bz",                       "whois.afilias-grs.info",
	"ca",                       "whois.cira.ca",
	"cc",                       "ccwhois.verisign-grs.com",
	"cd",                       "whois.nic.cd",
	"cf",                       "whois.dot.cf",
	"cg",                       DEFAULT_SERVER,
	"ch",                       "whois.nic.ch",
	"ci",                       "whois.nic.ci",
	"ck",                       "ck.whois-servers.net",
	"cl",                       "whois.nic.cl",
	"cm",                       "whois.netcom.cm",
	"cn",                       "whois.cnnic.cn",
	"co",                       "whois.nic.co",
	"cr",                       "whois.nic.cr",
	"cu",                       DEFAULT_SERVER,
	"cv",                       DEFAULT_SERVER,
	"cw",                       DEFAULT_SERVER,
	"cx",                       "whois.nic.cx",
	"cy",                       "cy.whois-servers.net",
	"cz",                       "whois.nic.cz",
	"de",                       "whois.denic.de",
	"dj",                       DEFAULT_SERVER,
	"dk",                       "whois.dk-hostmaster.dk",
	"dm",                       "whois.nic.dm",
	"do",                       "do.whois-servers.net",
	"dz",                       "whois.nic.dz",
	"ec",                       "whois.nic.ec",
	"ee",                       "whois.tld.ee",
	"eg",                       "eg.whois-servers.net",
	"er",                       DEFAULT_SERVER,
	"es",                       "whois.nic.es",
	"et",                       "whois.nic.et",
	"eu",                       "whois.eu",
	"fi",                       "whois.fi",
	"fj",                       "whois.usp.ac.fj",
	"fk",                       "whois.nic.fk",
	"fm",                       "whois.nic.fm",
	"fo",                       "whois.nic.fo",
	"fr",                       "whois.nic.fr",
	"ga",                       "whois.dot.ga",
	"gb",                       "gb.whois-servers.net",
	"gd",                       "whois.nic.gd",
	"ge",                       "whois.registration.ge",
	"gf",                       "whois.mediaserv.net",
	"gg",                       "whois.gg",
	"gh",                       "whois.nic.gh",
	"gi",                       "whois.afilias-grs.info",
	"gl",                       "whois.nic.gl",
	"gm",                       "gm.whois-servers.net",
	"gn",                       DEFAULT_SERVER,
	"gp",                       "gp.whois-servers.net",
	"gq",                       "whois.dominio.gq",
	"gr",                       "gr.whois-servers.net",
	"gs",                       "whois.nic.gs",
	"gt",                       DEFAULT_SERVER,
	"gu",                       DEFAULT_SERVER,
	"gw",                       DEFAULT_SERVER,
	"gy",                       "whois.registry.gy",
	"hk",                       "whois.hkirc.hk",
	"hm",                       "whois.registry.hm",
	"hn",                       "whois.nic.hn",
	"hr",                       "whois.dns.hr",
	"ht",                       "whois.nic.ht",
	"hu",                       "whois.nic.hu",
	"id",                       "whois.id",
	"ie",                       "whois.iedr.ie",
	"il",                       "whois.isoc.org.il",
	"im",                       "whois.nic.im",
	"in",                       "whois.inregistry.net",
	"io",                       "whois.nic.io",
	"iq",                       "whois.cmc.iq",
	"ir",                       "whois.nic.ir",
	"is",                       "whois.isnic.is",
	"it",                       "whois.nic.it",
	"je",                       "whois.je",
	"jm",                       DEFAULT_SERVER,
	"jo",                       "jo.whois-servers.net",
	"jp",                       JP_SERVER,
	"ke",                       "whois.kenic.or.ke",
	"kg",                       "whois.kg",
	"kh",                       DEFAULT_SERVER,
	"ki",                       "whois.nic.ki",
	"km",                       DEFAULT_SERVER,
	"kn",                       "whois.nic.kn",
	"kp",                       DEFAULT_SERVER,
	"kr",                       KR_SERVER,
	"kw",                       "whois.nic.kw",
	"ky",                       "whois.kyregistry.ky",
	"kz",                       "whois.nic.kz",
	"la",                       "whois.nic.la",
	"lb",                       DEFAULT_SERVER,
	"lc",                       "whois.afilias-grs.info",
	"li",                       "whois.nic.li",
	"lk",                       "whois.nic.lk",
	"lr",                       DEFAULT_SERVER,
	"ls",                       "whois.nic.ls",
	"lt",                       "whois.domreg.lt",
	"lu",                       "whois.dns.lu",
	"lv",                       "whois.nic.lv",
	"ly",                       "whois.nic.ly",
	"ma",                       "whois.registre.ma",
	"mc",                       "mc.whois-servers.net",
	"md",                       "whois.nic.md",
	"me",                       "whois.nic.me",
	"mg",                       "whois.nic.mg",
	"mh",                       DEFAULT_SERVER,
	"mk",                       "whois.marnet.mk",
	"ml",                       "whois.dot.ml",
	"mm",                       DEFAULT_SERVER,
	"mn",                       "whois.nic.mn",
	"mo",                       "whois.monic.mo",
	"mp",                       DEFAULT_SERVER,
	"mq",                       "whois.mediaserv.net",
	"mr",                       "whois.nic.mr",
	"ms",                       "whois.nic.ms",
	"mt",                       "mt.whois-servers.net",
	"mu",                       "whois.nic.mu",
	"mv",                       DEFAULT_SERVER,
	"mw",                       "whois.nic.mw",
	"mx",                       "whois.nic.mx",
	"my",                       "whois.mynic.my",
	"mz",                       "whois.nic.mz",
	"na",                       "whois.na-nic.com.na",
	"nc",                       "whois.nc",
	"ne",                       DEFAULT_SERVER,
	"nf",                       "whois.nic.nf",
	"ng",                       "whois.nic.net.ng",
	"ni",                       DEFAULT_SERVER,
	"nl",                       "whois.domain-registry.nl",
	"no",                       "whois.norid.no",
	"np",                       DEFAULT_SERVER,
	"nr",                       DEFAULT_SERVER,
	"nu",                       "whois.iis.nu",
	"nz",                       "whois.srs.net.nz",
	"om",                       "whois.registry.om",
	"pa",                       DEFAULT_SERVER,
	"pe",                       "kero.yachay.pe",
	"pf",                       "whois.registry.pf",
	"pg",                       DEFAULT_SERVER,
	"ph",                       DEFAULT_SERVER,
	"pk",                       DEFAULT_SERVER,
	"pl",                       "whois.dns.pl",
	"pm",                       "whois.nic.pm",
	"pn",                       DEFAULT_SERVER,
	"pr",                       "whois.afilias-srs.net",
	"ps",                       "whois.pnina.ps",
	"pt",                       "whois.dns.pt",
	"pw",                       "whois.nic.pw",
	"py",                       DEFAULT_SERVER,
	"qa",                       "whois.registry.qa",
	"re",                       "whois.nic.re",
	"ro",                       "whois.rotld.ro",
	"rs",                       "whois.rnids.rs",
	"ru",                       "whois.tcinet.ru",
	"rw",                       "whois.ricta.org.rw",
	"sa",                       "whois.nic.net.sa",
	"sb",                       "whois.nic.net.sb",
	"sc",                       "whois.afilias-grs.info",
	"sd",                       DEFAULT_SERVER,
	"se",                       "whois.iis.se",
	"sg",                       "whois.sgnic.sg",
	"sh",                       "whois.nic.sh",
	"si",                       "whois.register.si",
	"sj",                       DEFAULT_SERVER,
	"sk",                       "whois.sk-nic.sk",
	"sl",                       "whois.nic.sl",
	"sm",                       "whois.nic.sm",
	"sn",                       "whois.nic.sn",
	"so",                       "whois.nic.so",
	"sr",                       DEFAULT_SERVER,
	"st",                       "whois.nic.st",
	"su",                       "whois.tcinet.ru",
	"sv",                       DEFAULT_SERVER,
	"sx",                       "whois.sx",
	"sy",                       "whois.tld.sy",
	"sz",                       DEFAULT_SERVER,
	"tc",                       "whois.nic.tc",
	"td",                       DEFAULT_SERVER,
	"tf",                       "whois.nic.fr",
	"tg",                       "whois.nic.tg",
	"th",                       "whois.thnic.co.th",
	"tj",                       DEFAULT_SERVER,
	"tk",                       "whois.dot.tk",
	"tl",                       "whois.nic.tl",
	"tm",                       "whois.nic.tm",
	"tn",                       "whois.ati.tn",
	"to",                       "whois.tonic.to",
	"tr",                       "whois.nic.tr",
	"tt",                       DEFAULT_SERVER,
	"tv",                       "tvwhois.verisign-grs.com",
	"tw",                       "whois.twnic.net.tw",
	"tz",                       "whois.tznic.or.tz",
	"ua",                       "whois.ua",
	"ug",                       "whois.co.ug",
	"uk",                       "whois.nic.uk",
	"us",                       "whois.nic.us",
	"uy",                       "whois.nic.org.uy",
	"uz",                       "whois.cctld.uz",
	"va",                       "va.whois-servers.net",
	"vc",                       "whois.afilias-grs.info",
	"ve",                       "whois.nic.ve",
	"vg",                       "whois.nic.vg",
	"vi",                       DEFAULT_SERVER,
	"vn",                       DEFAULT_SERVER,
	"vu",                       "vunic.vu",
	"wf",                       "whois.nic.wf",
	"ws",                       "whois.website.ws",
	"ye",                       "whois.nic.ye",
	"yt",                       "whois.nic.yt",
	"za",                       "za.whois-servers.net",
	"zm",                       "whois.nic.zm",
	"zw",                       DEFAULT_SERVER,
	NULL, NULL
};

#include "new_gtlds.h"

#endif

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * End:
 * vim600: noet sw=4 ts=4 fdm=marker
 * vim<600: noet sw=4 ts=4
 */
