.\" RCSID: @(#)$Id: kwhois.1,v 1.1.1.1 2004-02-04 06:05:14 oops Exp $
.TH kwhois 1 "Oct 1999"
.SH Name
kwhois \- Korea finger\-style whois
.SH Intruduction
This package is modified to korean environment from origanl 
fwhois that was made by Chris Cappuccio <ccappuc@santafe.edu>.
.SH Syntax

Internic, Krnic, Tonic, eNic, JPnic :
.br
.B kwhois [domain name]

Except Internic, Krnic, Tonic, eNic, JPnic :
.br
.B kwhois [domain name]@[whois server]

.SH Description
The
.B kwhois 
is a korea finger-style whois for BSD systems and search Korea local domain.
It is smaller and more compact then the standard InterNIC whois.c, and 
also runs in a different manner. 
.B kwhois user@whois.internic.net 
would be the same as 
.B 'whois -h whois.internic.net user'. 
This command is espically useful in environments where 
different servers are queued, e.g. an organization with multiple 
whois servers running for different purposes. This type of 
command can also be useful when a user or group of users 
makes frequent use of many different whois servers. If a user 
simply types 'fwhois user' without a hostname, fwhois will 
automatically use host 
.B whois.internic.net
,
.B whois.krnic.net
,
.B whois.tonic.to
,
.B whois.nic.cc
and
.B whois.nic.ad.jp.
And other domain that was registered other NIC except Internic, 
Krnic, Tonic, eNIC and JPnic  use 'kwhois user@whois.server'.
.SH Restrictions
Not very useful if the server was compiled without SETPROCTITLE.
.SH FILES
.B /usr/bin/kwhois
.br
.B /usr/bin/whois
.SH BUG REPORT
Bug report to : 
.br
.B Byungki Lee <pino5@hitel.net>
.br
.B JoungKyun Kim <admin@oops.kr.net>
